### ISSUE TITLE
Infinite error loop when quitting web app run as internal application server

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#7]
I tried running the web app as an internal application server from the TUI. The web app popped up in my browser and seemed to work correctly. When I pressed `q` and `<enter>` in the TUI to close it, I got an infinite loop of errors.

[Here](http://somup.com/c0nYYtyefl)'s a short video.

What other information would you need to debug this?

**Comment by MrShoenel** [comment]
This problem was also fixed when fixing issue #6: The problem was that closing down the internal server would shut down the Asyncio loop, which the TUI relies on, too. This is not done any longer. Using the internal web server is only recommended during development for debugging purposes, so I removed this option when Metrics As Scores is installed as a package.

I did this because there cannot be a flawless coexistence between an internally hosted Bokeh server and a text-/console-based user interface (for example, shutting down the internal server may hang until the browser (tab) is closed).

However, I decided to leave the option for development purposes, as it is still a great way to debug the application. I do consider this fixed.

**Comment by mdhaber** [comment]
It no longer shows the infinite loop, but it does appear to freeze the `mas` tool.

**Comment by MrShoenel** [comment]
That happens as it waits for the browser to close the socket. That should occur when the tab is closed or the browser as a whole at the latest.

However, it may not be as reliable and the socket is only closed at some later, non-deterministic point in time. As I wrote earlier, the coexistence of a TUI and Bokeh's web server within the *same* Python process cannot be flawless, but I'd still like to keep this option as it is useful for debugging, even when the process may hang sometimes at shutdown (one can always just restart the debugging process).

I suggest marking this feature as experimental in the docs and TUI, as I would like to keep it. Would that be appropriate?

**Comment by mdhaber** [comment]
That's up to you, but I think there needs to be one option for running the web server locally that works well. Currently, I have problems with both.

**Comment by MrShoenel** [comment]
Absolutely, one needs to work. Once we figure out what the problem with the external process is, I will mark the embedded application as experimental and close this issue.

**Comment by MrShoenel** [comment]
Marked the internal (embedded) web server as experimental (725e829)
